#pragma once

#define SCREEN_WIDTH (1280)
#define SCREEN_HEIGHT (720) 
#define PLAYER_SIZE_COEFFICIENT 2.5f
#define FPS_STANTARD 60.0f

enum SCENE {
	SCENE_NONE,
	SCENE_TITLE,
	SCENE_MODE,
	SCENE_GAME,
	SCENE_RESULT,
	SCENE_RANKING,
};

void SetScene(SCENE s);
SCENE GetScene();